### ISSUE TITLE
Incompatible library version of QtWidgets

### ISSUE THREAD

**Issue by resaixe** [khrykin/StrategrDesktop#10]
Hey there. I cannot run the app on my Mac. The problem report prompts the following:

```
Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x3] Wrong version

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/QtWidgets.framework/Versions/5/QtWidgets
  Referenced from: /Applications/Strategr.app/Contents/MacOS/Strategr
  Reason: Incompatible library version: Strategr requires version 5.14.0 or later, 
  but QtWidgets provides version 5.7.0
```

My system is macOS Catalina 10.15.3, and QtWidgets's version is 5.7

```
    QtWidgets:

      Version: 5.7
      Obtained from: Unknown
      Last Modified: 9/5/18, 6:20 pm
      Kind: 64-bit
      Get Info String: Created by Qt/QMake
      Location: /Library/Frameworks/QtWidgets.framework
      Private: No
```

I updated Qt to the latest one via Homebrew, but it didn't affect the QtWidgets show by the system.

```
> brew info qt
qt: stable 5.14.1 (bottled), HEAD [keg-only]
Cross-platform application and UI framework
https://www.qt.io/
/usr/local/Cellar/qt/5.14.1 (10,389 files, 363.0MB)
```

Any thoughts on how to fix this?

**Comment by khrykin** [comment]
That's strange because the appropriate Qt version is bundled within the app. 
If you have some Qt versions installed manually and some via homebrew, they might conflict, you probably need to check this. However, Strategr shouldn't use system-installed Qt at all, thank you for the report!

**Comment by khrykin** [comment]
@resaixe Please check if you have some Qt-related .framework bundles or aliases in /Library/Frameworks. If so, you can delete them, or, more safely, move to ~/Library/Frameworks. I believe these are copied here only by Homebrew installation. 

Alternatively, you can run (given that Strategr is in Application folder)
```
install_name_tool -delete_rpath /Library/Frameworks /Applications/Strategr.app/Contents/MacOS/Strategr
```

**Comment by resaixe** [comment]
@khrykin Thanks for the quick reply! Your solution has helped (I used `install_name_tool ...` ).
The app is running ok now. Cheers!
