### ISSUE TITLE
Exporting to a single calendar

### ISSUE THREAD

**Issue by Kontor23** [khrykin/StrategrDesktop#3]
Hi,
I love the Strategr App.  I would like to have the possibility to export the activities to a calendar called Timeboxing for example and not to create a separate calendar for each activity. It would also be nice if Strategr could display the current calendar events with in the app. 

Thank you very much for your great work!

Resgars
MaK

**Comment by khrykin** [comment]
Hi, glad to hear that you enjoy the app! 
Exporting to a single calendar is definitely possible, I might even introduce this option in the next release. 
Implementing your second request, however, would be a bit more difficult, especially now, when I'm in the process of transferring the app to the mobile - so this might take more time, but I'll put this on a roadmap.

**Comment by khrykin** [comment]
Fixed in [v0.0.9](https://github.com/khrykin/StrategrDesktop/releases/tag/v0.0.9) Release.
