### ISSUE TITLE
opening a .stg file from finder creates 2 windows

### ISSUE THREAD

**Issue by borco** [khrykin/StrategrDesktop#7]
In Finder, double-click on an **.stg** file. The app will open it, but it will also open a window with title **Untitled** (with no activities), as in the screenshots bellow.

![Screenshot 2020-02-08 at 18 01 13](https://user-images.githubusercontent.com/1324836/74088271-19b78580-4a9d-11ea-8a1c-63ef5d2bf76e.png)

![Screenshot 2020-02-08 at 18 00 16](https://user-images.githubusercontent.com/1324836/74088263-e5dc6000-4a9c-11ea-9528-9116ade7f8f8.png)

**Comment by khrykin** [comment]
@borco Thank you for reporting, unfortunately, I can't reproduce this is on my machine with the latest release (v0.0.7).  Can you please give more context, macOS version?

**Comment by borco** [comment]
macOS Catalina: 10.15.3 (19D76)
Qt: 5.14.1

**Comment by khrykin** [comment]
@borco Can you  find out which minimal timeout here would resolve the issue on your system?:
https://github.com/khrykin/StrategrDesktop/blob/a669ff5d7f21f5e1e79d2b87c391ecbbcd0a1b0f/ui/application.cpp#L19

**Comment by borco** [comment]
Using QTimer for this doesn't look right to me.

Instead, I would:

* make a public method to load an stg file and replace the current one, if is one already loaded by the app
* call the method to load the last .stg, like now, on startup
* call it to replace the current .stg with that from Finder, if invoked via finder

something like:

```
class Application ... {
...
signals:
  void loadStrategy(const QString&); // emitted when clicking on .stg in Finder
...
}

class MainWindow ... {
...
public:
  void onLoadStrategy(const QString&); // can replace loaded stg with another one
...
}

main() {

...
QObject::connect(&a, &Application::loadStrategy, &window, &MainWindow::onLoadStrategy);
...
}
```

**Comment by borco** [comment]
Btw, I've looked again in your code and you're actually creating the window inside your custom Application class - so you should probably move that connect there...

**Comment by khrykin** [comment]
@borco It was done this way in the past, but I introduced QTimer to eliminate "blinking" when the default strategy was visible for a split second if opening from a file.

**Comment by borco** [comment]
Yes, blinking might happen - hanven't thought about it.

Have you tried to load the default strategy when the window is shown the first time if other strategy is not already loaded? Haven't tested it myself, but the signal from Finder might come before the main window is actually shown...

QTimer definitely doesn't look right to me, but I guess you can use it until you find a better strategy...

**Comment by khrykin** [comment]
@borco `QFileOpenEvent` fires after `QApplication` starts, so there is no way of knowing beforehand if the app was started by clicking on a file or just by itself on a macOS. One way or another - we still need to wait for some time to check if `QFileOpenEvent` actually has been fired, if we don't want the blinking.

**Comment by borco** [comment]
Than just put some msec (like 500msec) in QTimer... I'm curious how a native Swift/Objective-C app would handle this...

**Comment by khrykin** [comment]
@borco there is 100ms in v0.0.9 , can you please check the new version? 
Native apps can have [`application:openFile:`](https://developer.apple.com/documentation/appkit/nsapplicationdelegate/1428612-application?language=objc) in the app's delegate and you can handle this situation appropriately, but unfortunately, as far as I know, in Qt there is no `applicationDidFinishLaunching:` event analog.

**Comment by borco** [comment]
Would this help? https://wiki.qt.io/Application_Start-up_Patterns

**Comment by khrykin** [comment]
I think using native event loop and manually hooking Qt into it would be a "kill a fly with a sledgehammer" type of solution for this particular problem. 😀

**Comment by borco** [comment]
master isn't building for me.

```
[ 51%] Building CXX object CMakeFiles/ui_tests.dir/ui/macoswindow.mm.o
/Users/borco/Developer/StrategrDesktop/ui/macoswindow.mm:13:10: fatal error: 'QtMac' file not found
#include <QtMac>
         ^~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/ui_tests.dir/ui/macoswindow.mm.o] Error 1
make[1]: *** [CMakeFiles/ui_tests.dir/all] Error 2
make: *** [all] Error 2
19:16:07: The process "/usr/local/Cellar/cmake/3.16.2/bin/cmake" exited with code 2.
Error while building/deploying project Strategr (kit: Desktop Qt 5.14.1 clang 64bit)
When executing step "CMake Build"
```

this was one of the things fixed in my pull request, but that can no longer be applied as your code changed.

btw, your project looks interesting, but unfortunately i can't dedicate this much time to it. please feel free to close my tickets as you feel appropriate. br.

**Comment by khrykin** [comment]
I'll fix this thank you, "Strategr" target should build, however.
